#!/usr/bin/env bash
# =============================================================================
# Module 05 — Kernel Parameter Hardening (sysctl)
# All parameters are written to /etc/sysctl.d/99-hardening.conf
# and applied immediately with sysctl --system.
# =============================================================================
set -euo pipefail

echo "[05] Applying kernel hardening parameters..."

SYSCTL_FILE="/etc/sysctl.d/99-hardening.conf"

cat > "$SYSCTL_FILE" <<'EOF'
# ===========================================================================
# Kernel hardening — generated by hardening suite
# ===========================================================================

# ── Kernel self-protection ──────────────────────────────────────────────────
# Restrict ptrace to parent processes only
kernel.yama.ptrace_scope = 1
# Hide kernel pointers from unprivileged users
kernel.kptr_restrict = 2
# Restrict dmesg to root
kernel.dmesg_restrict = 1
# Disable the SysRq key
kernel.sysrq = 0
# Prevent core dumps containing setuid program memory
fs.suid_dumpable = 0
# Disable the creation of hardlinks/symlinks to files the user doesn't own
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
# Restrict /proc/<pid>/* to file owner and root
kernel.unprivileged_userns_clone = 0

# ── Address Space Layout Randomisation ─────────────────────────────────────
kernel.randomize_va_space = 2

# ── Network: IP spoofing & source routing ──────────────────────────────────
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# ── Network: ICMP ───────────────────────────────────────────────────────────
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1
net.ipv4.icmp_echo_ignore_all = 0

# ── Network: SYN flood protection ──────────────────────────────────────────
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_max_syn_backlog = 4096

# ── Network: TCP hardening ──────────────────────────────────────────────────
# Reduce TIME_WAIT sockets
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_tw_reuse = 1
# Ignore TCP RST packets with out-of-window sequence numbers
net.ipv4.tcp_rfc1337 = 1
# Keep alive tuning
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_probes = 3
net.ipv4.tcp_keepalive_intvl = 30

# ── Network: routing & forwarding ──────────────────────────────────────────
# Disable packet forwarding (re-enable if this is a router/container host)
net.ipv4.ip_forward = 0
net.ipv4.conf.all.forwarding = 0

# ── IPv6 (disable if not in use) ────────────────────────────────────────────
# Comment these out if IPv6 is required.
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_source_route = 0

# ── Memory / exec protection ─────────────────────────────────────────────────
# Restrict mmap base address
vm.mmap_min_addr = 65536

# ── File descriptor & inotify limits ─────────────────────────────────────────
fs.file-max = 2097152
fs.inotify.max_user_watches = 524288
EOF

chmod 644 "$SYSCTL_FILE"

# Apply immediately
sysctl --system 2>&1 | grep -v "^sysctl" | grep -v "^$" || true
echo "  sysctl parameters applied."

echo "[05] Kernel parameter hardening complete."
